//! The standard file table (generated; see names.rs).

// Generated from TS 31.102 / 31.103 / 51.011 / 102.221 and cross-checked against pySim (ts_31_102.py, ts_31_103.py,
// ts_51_011.py, ts_102_221.py): every (name, FID) that pySim defines is in this table with the same FID.

/// Standard directories: name, identifier, parent scope.
pub const DIRS: &[(&str, u16, &str)] = &[
    ("MF", 0x3F00, ""),
    ("DF.TELECOM", 0x7F10, "MF"),
    ("DF.GSM", 0x7F20, "MF"),
    ("DF.PHONEBOOK", 0x5F3A, "DF.TELECOM"),
    ("DF.GRAPHICS", 0x5F50, "DF.TELECOM"),
    ("DF.MULTIMEDIA", 0x5F3B, "DF.TELECOM"),
    ("DF.MCS", 0x5F3D, "DF.TELECOM"),
    ("DF.SoLSA", 0x5F70, "DF.GSM"),
    ("DF.MExE", 0x5F3E, "DF.GSM"),
    ("DF.GSM-ACCESS", 0x5F3B, "ADF.USIM"),
    ("DF.5GS", 0x5FC0, "ADF.USIM"),
    ("DF.SAIP", 0x5FD0, "ADF.USIM"),
    ("DF.WLAN", 0x5F40, "ADF.USIM"),
    ("DF.HNB", 0x5F50, "ADF.USIM"),
    ("DF.ProSe", 0x5F90, "ADF.USIM"),
    ("DF.SNPN", 0x5FE0, "ADF.USIM"),
    ("DF.5G_ProSe", 0x5FF0, "ADF.USIM"),
    ("DF.5MBSUECONFIG", 0x5FF1, "ADF.USIM"),
];

/// Standard elementary files: scope, name, identifier, structure (T/L/C/B), decoder, description.
pub const EFS: &[(&str, &str, u16, char, &str, &str)] = &[
    (
        "ADF.ISIM",
        "EF.IMPI",
        0x6F02,
        'T',
        "impi",
        "IMS private user identity",
    ),
    (
        "ADF.ISIM",
        "EF.DOMAIN",
        0x6F03,
        'T',
        "uri",
        "Home network domain name",
    ),
    (
        "ADF.ISIM",
        "EF.IMPU",
        0x6F04,
        'L',
        "impu",
        "IMS public user identity",
    ),
    (
        "ADF.ISIM",
        "EF.ARR",
        0x6F06,
        'L',
        "tlv",
        "Access rule reference",
    ),
    (
        "ADF.ISIM",
        "EF.IST",
        0x6F07,
        'T',
        "services",
        "ISIM service table",
    ),
    (
        "ADF.ISIM",
        "EF.PCSCF",
        0x6F09,
        'L',
        "pcscf",
        "P-CSCF address",
    ),
    ("ADF.ISIM", "EF.SMS", 0x6F3C, 'L', "sms", "Short messages"),
    (
        "ADF.ISIM",
        "EF.SMSP",
        0x6F42,
        'L',
        "smsp",
        "Short message service parameters",
    ),
    ("ADF.ISIM", "EF.SMSS", 0x6F43, 'T', "smss", "SMS status"),
    (
        "ADF.ISIM",
        "EF.SMSR",
        0x6F47,
        'L',
        "hex",
        "Short message status reports",
    ),
    (
        "ADF.ISIM",
        "EF.AD",
        0x6FAD,
        'T',
        "ad",
        "Administrative data",
    ),
    (
        "ADF.ISIM",
        "EF.GBABP",
        0x6FD6,
        'T',
        "hex",
        "GBA bootstrapping parameters",
    ),
    ("ADF.ISIM", "EF.GBANL", 0x6FDA, 'L', "tlv", "GBA NAF list"),
    (
        "ADF.ISIM",
        "EF.NAFKCA",
        0x6FDD,
        'L',
        "tlv",
        "NAF key centre address",
    ),
    ("ADF.ISIM", "EF.UICCIARI", 0x6FE7, 'L', "tlv", "UICC IARI"),
    (
        "ADF.ISIM",
        "EF.FromPreferred",
        0x6FF7,
        'T',
        "uint",
        "From preferred",
    ),
    (
        "ADF.ISIM",
        "EF.IMSConfigData",
        0x6FF8,
        'B',
        "tlv",
        "IMS configuration data",
    ),
    ("ADF.ISIM", "EF.WebRTCURI", 0x6FFA, 'T', "tlv", "WebRTC URI"),
    (
        "ADF.ISIM",
        "EF.XCAPConfigData",
        0x6FFC,
        'B',
        "tlv",
        "XCAP configuration data",
    ),
    ("ADF.USIM", "EF.EAKA", 0x6F01, 'T', "hex", "EAP-AKA"),
    (
        "ADF.USIM",
        "EF.OCST",
        0x6F02,
        'T',
        "hex",
        "Operator controlled service table",
    ),
    (
        "ADF.USIM",
        "EF.LI",
        0x6F05,
        'T',
        "alpha-list",
        "Language indication",
    ),
    (
        "ADF.USIM",
        "EF.ARR",
        0x6F06,
        'L',
        "tlv",
        "Access rule reference",
    ),
    ("ADF.USIM", "EF.IMSI", 0x6F07, 'T', "imsi", "IMSI"),
    (
        "ADF.USIM",
        "EF.Keys",
        0x6F08,
        'T',
        "hex",
        "Ciphering and integrity keys",
    ),
    (
        "ADF.USIM",
        "EF.KeysPS",
        0x6F09,
        'T',
        "hex",
        "Ciphering and integrity keys for packet switched domain",
    ),
    (
        "ADF.USIM",
        "EF.DCK",
        0x6F2C,
        'T',
        "hex",
        "De-personalization control keys",
    ),
    (
        "ADF.USIM",
        "EF.HPPLMN",
        0x6F31,
        'T',
        "uint",
        "Higher priority PLMN search period",
    ),
    (
        "ADF.USIM",
        "EF.CNL",
        0x6F32,
        'T',
        "hex",
        "Co-operative network list",
    ),
    (
        "ADF.USIM",
        "EF.ACMmax",
        0x6F37,
        'T',
        "uint",
        "ACM maximum value",
    ),
    (
        "ADF.USIM",
        "EF.UST",
        0x6F38,
        'T',
        "services",
        "USIM service table",
    ),
    (
        "ADF.USIM",
        "EF.ACM",
        0x6F39,
        'C',
        "uint",
        "Accumulated call meter",
    ),
    (
        "ADF.USIM",
        "EF.FDN",
        0x6F3B,
        'L',
        "adn",
        "Fixed dialling numbers",
    ),
    ("ADF.USIM", "EF.SMS", 0x6F3C, 'L', "sms", "Short messages"),
    (
        "ADF.USIM",
        "EF.GID1",
        0x6F3E,
        'T',
        "hex",
        "Group identifier level 1",
    ),
    (
        "ADF.USIM",
        "EF.GID2",
        0x6F3F,
        'T',
        "hex",
        "Group identifier level 2",
    ),
    ("ADF.USIM", "EF.MSISDN", 0x6F40, 'L', "adn", "MSISDN"),
    (
        "ADF.USIM",
        "EF.PUCT",
        0x6F41,
        'T',
        "hex",
        "Price per unit and currency table",
    ),
    (
        "ADF.USIM",
        "EF.SMSP",
        0x6F42,
        'L',
        "smsp",
        "Short message service parameters",
    ),
    ("ADF.USIM", "EF.SMSS", 0x6F43, 'T', "smss", "SMS status"),
    (
        "ADF.USIM",
        "EF.CBMI",
        0x6F45,
        'T',
        "cbmi",
        "Cell broadcast message identifier selection",
    ),
    (
        "ADF.USIM",
        "EF.SPN",
        0x6F46,
        'T',
        "spn",
        "Service provider name",
    ),
    (
        "ADF.USIM",
        "EF.SMSR",
        0x6F47,
        'L',
        "hex",
        "Short message status reports",
    ),
    (
        "ADF.USIM",
        "EF.CBMID",
        0x6F48,
        'T',
        "cbmi",
        "Cell broadcast message identifier for data download",
    ),
    (
        "ADF.USIM",
        "EF.SDN",
        0x6F49,
        'L',
        "adn",
        "Service dialling numbers",
    ),
    ("ADF.USIM", "EF.EXT2", 0x6F4B, 'L', "hex", "Extension 2"),
    ("ADF.USIM", "EF.EXT3", 0x6F4C, 'L', "hex", "Extension 3"),
    (
        "ADF.USIM",
        "EF.BDN",
        0x6F4D,
        'L',
        "adn",
        "Barred dialling numbers",
    ),
    ("ADF.USIM", "EF.EXT5", 0x6F4E, 'L', "hex", "Extension 5"),
    (
        "ADF.USIM",
        "EF.CCP2",
        0x6F4F,
        'L',
        "hex",
        "Capability configuration parameters 2",
    ),
    (
        "ADF.USIM",
        "EF.CBMIR",
        0x6F50,
        'T',
        "cbmi",
        "Cell broadcast message identifier range selection",
    ),
    ("ADF.USIM", "EF.EXT4", 0x6F55, 'L', "hex", "Extension 4"),
    (
        "ADF.USIM",
        "EF.EST",
        0x6F56,
        'T',
        "services",
        "Enabled services table",
    ),
    ("ADF.USIM", "EF.ACL", 0x6F57, 'T', "acl", "APN control list"),
    (
        "ADF.USIM",
        "EF.CMI",
        0x6F58,
        'L',
        "hex",
        "Comparison method information",
    ),
    (
        "ADF.USIM",
        "EF.START-HFN",
        0x6F5B,
        'T',
        "hex",
        "Initialisation values for hyperframe number",
    ),
    (
        "ADF.USIM",
        "EF.THRESHOLD",
        0x6F5C,
        'T',
        "hex",
        "Maximum value of START",
    ),
    (
        "ADF.USIM",
        "EF.PLMNwAcT",
        0x6F60,
        'T',
        "plmn-act",
        "User controlled PLMN selector with access technology",
    ),
    (
        "ADF.USIM",
        "EF.OPLMNwAcT",
        0x6F61,
        'T',
        "plmn-act",
        "Operator controlled PLMN selector with access technology",
    ),
    (
        "ADF.USIM",
        "EF.HPLMNwAcT",
        0x6F62,
        'T',
        "plmn-act",
        "HPLMN selector with access technology",
    ),
    (
        "ADF.USIM",
        "EF.RPLMNAcT",
        0x6F65,
        'T',
        "plmn-act",
        "RPLMN last used access technology",
    ),
    (
        "ADF.USIM",
        "EF.RPLMNActD",
        0x6F65,
        'T',
        "hex",
        "RPLMN last used access technology (dedicated)",
    ),
    (
        "ADF.USIM",
        "EF.PSLOCI",
        0x6F73,
        'T',
        "loci",
        "Packet switched location information",
    ),
    (
        "ADF.USIM",
        "EF.ACC",
        0x6F78,
        'T',
        "acc",
        "Access control class",
    ),
    (
        "ADF.USIM",
        "EF.FPLMN",
        0x6F7B,
        'T',
        "plmn-list",
        "Forbidden PLMNs",
    ),
    (
        "ADF.USIM",
        "EF.LOCI",
        0x6F7E,
        'T',
        "loci",
        "Location information",
    ),
    (
        "ADF.USIM",
        "EF.ICI",
        0x6F80,
        'C',
        "hex",
        "Incoming call information",
    ),
    (
        "ADF.USIM",
        "EF.OCI",
        0x6F81,
        'C',
        "hex",
        "Outgoing call information",
    ),
    (
        "ADF.USIM",
        "EF.ICT",
        0x6F82,
        'C',
        "uint",
        "Incoming call timer",
    ),
    (
        "ADF.USIM",
        "EF.OCT",
        0x6F83,
        'C',
        "uint",
        "Outgoing call timer",
    ),
    (
        "ADF.USIM",
        "EF.AD",
        0x6FAD,
        'T',
        "ad",
        "Administrative data",
    ),
    (
        "ADF.USIM",
        "EF.VGCS",
        0x6FB1,
        'T',
        "hex",
        "Voice group call service",
    ),
    (
        "ADF.USIM",
        "EF.VGCSS",
        0x6FB2,
        'T',
        "hex",
        "Voice group call service status",
    ),
    (
        "ADF.USIM",
        "EF.VBS",
        0x6FB3,
        'T',
        "hex",
        "Voice broadcast service",
    ),
    (
        "ADF.USIM",
        "EF.VBSS",
        0x6FB4,
        'T',
        "hex",
        "Voice broadcast service status",
    ),
    (
        "ADF.USIM",
        "EF.eMLPP",
        0x6FB5,
        'T',
        "hex",
        "Enhanced multi level pre-emption and priority",
    ),
    (
        "ADF.USIM",
        "EF.AAeM",
        0x6FB6,
        'T',
        "hex",
        "Automatic answer for eMLPP service",
    ),
    (
        "ADF.USIM",
        "EF.ECC",
        0x6FB7,
        'L',
        "ecc",
        "Emergency call codes",
    ),
    (
        "ADF.USIM",
        "EF.Hiddenkey",
        0x6FC3,
        'T',
        "hex",
        "Key for hidden phone book entries",
    ),
    (
        "ADF.USIM",
        "EF.NETPAR",
        0x6FC4,
        'T',
        "hex",
        "Network parameters",
    ),
    (
        "ADF.USIM",
        "EF.PNN",
        0x6FC5,
        'L',
        "tlv",
        "PLMN network name",
    ),
    (
        "ADF.USIM",
        "EF.OPL",
        0x6FC6,
        'L',
        "opl",
        "Operator PLMN list",
    ),
    (
        "ADF.USIM",
        "EF.MBDN",
        0x6FC7,
        'L',
        "adn",
        "Mailbox dialling numbers",
    ),
    ("ADF.USIM", "EF.EXT6", 0x6FC8, 'L', "hex", "Extension 6"),
    (
        "ADF.USIM",
        "EF.MBI",
        0x6FC9,
        'L',
        "hex",
        "Mailbox identifier",
    ),
    (
        "ADF.USIM",
        "EF.MWIS",
        0x6FCA,
        'L',
        "hex",
        "Message waiting indication status",
    ),
    (
        "ADF.USIM",
        "EF.CFIS",
        0x6FCB,
        'L',
        "hex",
        "Call forwarding indication status",
    ),
    ("ADF.USIM", "EF.EXT7", 0x6FCC, 'L', "hex", "Extension 7"),
    (
        "ADF.USIM",
        "EF.SPDI",
        0x6FCD,
        'T',
        "tlv",
        "Service provider display information",
    ),
    (
        "ADF.USIM",
        "EF.MMSN",
        0x6FCE,
        'L',
        "hex",
        "MMS notification",
    ),
    ("ADF.USIM", "EF.EXT8", 0x6FCF, 'L', "hex", "Extension 8"),
    (
        "ADF.USIM",
        "EF.MMSICP",
        0x6FD0,
        'T',
        "tlv",
        "MMS issuer connectivity parameters",
    ),
    (
        "ADF.USIM",
        "EF.MMSUP",
        0x6FD1,
        'L',
        "hex",
        "MMS user preferences",
    ),
    (
        "ADF.USIM",
        "EF.MMSUCP",
        0x6FD2,
        'T',
        "tlv",
        "MMS user connectivity parameters",
    ),
    (
        "ADF.USIM",
        "EF.NIA",
        0x6FD3,
        'L',
        "hex",
        "Network indication of alerting",
    ),
    (
        "ADF.USIM",
        "EF.VGCSCA",
        0x6FD4,
        'T',
        "hex",
        "VGCS certificates",
    ),
    (
        "ADF.USIM",
        "EF.VBSCA",
        0x6FD5,
        'T',
        "hex",
        "VBS certificates",
    ),
    (
        "ADF.USIM",
        "EF.GBABP",
        0x6FD6,
        'T',
        "hex",
        "GBA bootstrapping parameters",
    ),
    (
        "ADF.USIM",
        "EF.MSK",
        0x6FD7,
        'L',
        "hex",
        "MBMS service keys",
    ),
    ("ADF.USIM", "EF.MUK", 0x6FD8, 'L', "tlv", "MBMS user key"),
    (
        "ADF.USIM",
        "EF.EHPLMN",
        0x6FD9,
        'T',
        "plmn-list",
        "Equivalent HPLMN",
    ),
    ("ADF.USIM", "EF.GBANL", 0x6FDA, 'L', "tlv", "GBA NAF list"),
    (
        "ADF.USIM",
        "EF.EHPLMNPI",
        0x6FDB,
        'T',
        "uint",
        "Equivalent HPLMN presentation indication",
    ),
    (
        "ADF.USIM",
        "EF.LRPLMNSI",
        0x6FDC,
        'T',
        "uint",
        "Last RPLMN selection indication",
    ),
    (
        "ADF.USIM",
        "EF.NAFKCA",
        0x6FDD,
        'L',
        "tlv",
        "NAF key centre address",
    ),
    (
        "ADF.USIM",
        "EF.SPNI",
        0x6FDE,
        'L',
        "tlv",
        "Service provider name icon",
    ),
    (
        "ADF.USIM",
        "EF.PNNI",
        0x6FDF,
        'L',
        "tlv",
        "PLMN network name icon",
    ),
    (
        "ADF.USIM",
        "EF.NCP-IP",
        0x6FE2,
        'L',
        "tlv",
        "Network connectivity parameters for USIM IP connections",
    ),
    (
        "ADF.USIM",
        "EF.EPSLOCI",
        0x6FE3,
        'T',
        "loci",
        "EPS location information",
    ),
    (
        "ADF.USIM",
        "EF.EPSNSC",
        0x6FE4,
        'L',
        "tlv",
        "EPS NAS security context",
    ),
    (
        "ADF.USIM",
        "EF.UFC",
        0x6FE6,
        'T',
        "hex",
        "USAT facility control",
    ),
    ("ADF.USIM", "EF.UICCIARI", 0x6FE7, 'L', "tlv", "UICC IARI"),
    ("ADF.USIM", "EF.NASCONFIG", 0x6FE8, 'T', "tlv", "NAS config"),
    (
        "ADF.USIM",
        "EF.PWS",
        0x6FEC,
        'T',
        "hex",
        "Public warning system",
    ),
    (
        "ADF.USIM",
        "EF.FDNURI",
        0x6FED,
        'L',
        "tlv",
        "Fixed dialling numbers URI",
    ),
    (
        "ADF.USIM",
        "EF.BDNURI",
        0x6FEE,
        'L',
        "tlv",
        "Barred dialling numbers URI",
    ),
    (
        "ADF.USIM",
        "EF.SDNURI",
        0x6FEF,
        'L',
        "tlv",
        "Service dialling numbers URI",
    ),
    ("ADF.USIM", "EF.IWL", 0x6FF0, 'L', "tlv", "Index of WLAN"),
    (
        "ADF.USIM",
        "EF.IPS",
        0x6FF1,
        'C',
        "hex",
        "IMEI(SV) pairing status",
    ),
    (
        "ADF.USIM",
        "EF.IPD",
        0x6FF2,
        'L',
        "hex",
        "IMEI(SV) of pairing device",
    ),
    (
        "ADF.USIM",
        "EF.ePDGId",
        0x6FF3,
        'T',
        "tlv",
        "Home ePDG identifier",
    ),
    (
        "ADF.USIM",
        "EF.ePDGSelection",
        0x6FF4,
        'T',
        "tlv",
        "ePDG selection information",
    ),
    (
        "ADF.USIM",
        "EF.ePDGIdEm",
        0x6FF5,
        'T',
        "tlv",
        "Emergency ePDG identifier",
    ),
    (
        "ADF.USIM",
        "EF.ePDGSelectionEm",
        0x6FF6,
        'T',
        "tlv",
        "Emergency ePDG selection information",
    ),
    (
        "ADF.USIM",
        "EF.FromPreferred",
        0x6FF7,
        'T',
        "uint",
        "From preferred",
    ),
    (
        "ADF.USIM",
        "EF.IMSConfigData",
        0x6FF8,
        'B',
        "tlv",
        "IMS configuration data",
    ),
    (
        "ADF.USIM",
        "EF.3GPPPSDATAOFF",
        0x6FF9,
        'T',
        "hex",
        "3GPP PS data off",
    ),
    (
        "ADF.USIM",
        "EF.3GPPPSDATAOFFservicelist",
        0x6FFA,
        'L',
        "hex",
        "3GPP PS data off service list",
    ),
    (
        "ADF.USIM",
        "EF.TVCONFIG",
        0x6FFB,
        'B',
        "tlv",
        "TV configuration",
    ),
    (
        "ADF.USIM",
        "EF.XCAPCONFIGDATA",
        0x6FFC,
        'B',
        "tlv",
        "XCAP configuration data",
    ),
    (
        "ADF.USIM",
        "EF.EARFCNLIST",
        0x6FFD,
        'T',
        "tlv",
        "EARFCN list for MTC/NB-IOT UEs",
    ),
    (
        "ADF.USIM",
        "EF.MudMidConfigData",
        0x6FFE,
        'B',
        "tlv",
        "MUD and MID configuration data",
    ),
    (
        "DF.5GS",
        "EF.5GS3GPPLOCI",
        0x4F01,
        'T',
        "hex",
        "5GS 3GPP location information",
    ),
    (
        "DF.5GS",
        "EF.5GSN3GPPLOCI",
        0x4F02,
        'T',
        "hex",
        "5GS non-3GPP location information",
    ),
    (
        "DF.5GS",
        "EF.5GS3GPPNSC",
        0x4F03,
        'L',
        "tlv",
        "5GS 3GPP access NAS security context",
    ),
    (
        "DF.5GS",
        "EF.5GSN3GPPNSC",
        0x4F04,
        'L',
        "tlv",
        "5GS non-3GPP access NAS security context",
    ),
    (
        "DF.5GS",
        "EF.5GAUTHKEYS",
        0x4F05,
        'T',
        "tlv",
        "5G authentication keys",
    ),
    (
        "DF.5GS",
        "EF.UAC_AIC",
        0x4F06,
        'T',
        "hex",
        "UAC access identities configuration",
    ),
    (
        "DF.5GS",
        "EF.SUCI_Calc_Info",
        0x4F07,
        'T',
        "suci",
        "SUCI calculation information",
    ),
    (
        "DF.5GS",
        "EF.OPL5G",
        0x4F08,
        'L',
        "hex",
        "Operator PLMN list for 5GS",
    ),
    ("DF.5GS", "EF.SUPI_NAI", 0x4F09, 'T', "tlv", "SUPI as NAI"),
    (
        "DF.5GS",
        "EF.Routing_Indicator",
        0x4F0A,
        'T',
        "routing-ind",
        "Routing indicator",
    ),
    (
        "DF.5GS",
        "EF.URSP",
        0x4F0B,
        'B',
        "tlv",
        "UE route selection policy",
    ),
    (
        "DF.5GS",
        "EF.TN3GPPSNN",
        0x4F0C,
        'T',
        "hex",
        "Trusted non-3GPP access network name",
    ),
    (
        "DF.5GS",
        "EF.CAG",
        0x4F0D,
        'T',
        "tlv",
        "Closed access group information",
    ),
    (
        "DF.5GS",
        "EF.SOR-CMCI",
        0x4F0E,
        'T',
        "tlv",
        "Steering of roaming connected mode control information",
    ),
    (
        "DF.5GS",
        "EF.DRI",
        0x4F0F,
        'T',
        "hex",
        "Disaster roaming information",
    ),
    (
        "DF.5GS",
        "EF.5GSEDRX",
        0x4F10,
        'T',
        "hex",
        "5GS eDRX parameters",
    ),
    (
        "DF.5GS",
        "EF.5GNSWO_CONF",
        0x4F11,
        'T',
        "hex",
        "5GS non-seamless WLAN offload configuration",
    ),
    (
        "DF.5GS",
        "EF.MCHPPLMN",
        0x4F15,
        'T',
        "uint",
        "Multimedia call higher priority PLMN",
    ),
    (
        "DF.5GS",
        "EF.KAUSF_DERIVATION",
        0x4F16,
        'T',
        "hex",
        "K_AUSF derivation configuration",
    ),
    (
        "DF.5G_ProSe",
        "EF.5G_PROSE_ST",
        0x4F01,
        'T',
        "hex",
        "5G ProSe service table",
    ),
    (
        "DF.5G_ProSe",
        "EF.5G_PROSE_DD",
        0x4F02,
        'T',
        "hex",
        "5G ProSe direct discovery configuration",
    ),
    (
        "DF.5G_ProSe",
        "EF.5G_PROSE_DC",
        0x4F03,
        'T',
        "hex",
        "5G ProSe direct communication configuration",
    ),
    (
        "DF.5G_ProSe",
        "EF.5G_PROSE_U2NRU",
        0x4F04,
        'T',
        "hex",
        "5G ProSe UE-to-network relay UE configuration",
    ),
    (
        "DF.5G_ProSe",
        "EF.5G_PROSE_RU",
        0x4F05,
        'T',
        "hex",
        "5G ProSe remote UE configuration",
    ),
    (
        "DF.5G_ProSe",
        "EF.5G_PROSE_UIR",
        0x4F06,
        'T',
        "hex",
        "5G ProSe usage information reporting",
    ),
    (
        "DF.5G_ProSe",
        "EF.5G_PROSE_U2URU",
        0x4F07,
        'T',
        "hex",
        "5G ProSe UE-to-UE relay UE configuration",
    ),
    (
        "DF.5G_ProSe",
        "EF.5G_PROSE_EU",
        0x4F08,
        'T',
        "hex",
        "5G ProSe end UE configuration",
    ),
    (
        "DF.5MBSUECONFIG",
        "EF.5MBSUECONFIG",
        0x4F01,
        'T',
        "hex",
        "5MBS UE configuration",
    ),
    (
        "DF.GRAPHICS",
        "EF.IMG",
        0x4F20,
        'L',
        "hex",
        "Image instance data",
    ),
    ("DF.GSM", "EF.LP", 0x6F05, 'T', "hex", "Language preference"),
    ("DF.GSM", "EF.IMSI", 0x6F07, 'T', "imsi", "IMSI"),
    (
        "DF.GSM",
        "EF.Kc",
        0x6F20,
        'T',
        "hex",
        "Ciphering key Kc and sequence number",
    ),
    (
        "DF.GSM",
        "EF.PLMNsel",
        0x6F30,
        'T',
        "plmn-list",
        "PLMN selector",
    ),
    (
        "DF.GSM",
        "EF.HPPLMN",
        0x6F31,
        'T',
        "uint",
        "Higher priority PLMN search period",
    ),
    (
        "DF.GSM",
        "EF.ACMmax",
        0x6F37,
        'T',
        "uint",
        "ACM maximum value",
    ),
    (
        "DF.GSM",
        "EF.SST",
        0x6F38,
        'T',
        "services",
        "SIM service table",
    ),
    (
        "DF.GSM",
        "EF.ACM",
        0x6F39,
        'C',
        "uint",
        "Accumulated call meter",
    ),
    (
        "DF.GSM",
        "EF.GID1",
        0x6F3E,
        'T',
        "hex",
        "Group identifier level 1",
    ),
    (
        "DF.GSM",
        "EF.GID2",
        0x6F3F,
        'T',
        "hex",
        "Group identifier level 2",
    ),
    (
        "DF.GSM",
        "EF.PUCT",
        0x6F41,
        'T',
        "hex",
        "Price per unit and currency table",
    ),
    (
        "DF.GSM",
        "EF.CBMI",
        0x6F45,
        'T',
        "cbmi",
        "Cell broadcast message identifier selection",
    ),
    (
        "DF.GSM",
        "EF.SPN",
        0x6F46,
        'T',
        "spn",
        "Service provider name",
    ),
    (
        "DF.GSM",
        "EF.CBMID",
        0x6F48,
        'T',
        "cbmi",
        "Cell broadcast message identifier for data download",
    ),
    (
        "DF.GSM",
        "EF.CBMIR",
        0x6F50,
        'T',
        "cbmi",
        "Cell broadcast message identifier range selection",
    ),
    (
        "DF.GSM",
        "EF.NIA",
        0x6F51,
        'L',
        "hex",
        "Network indication of alerting",
    ),
    (
        "DF.GSM",
        "EF.KcGPRS",
        0x6F52,
        'T',
        "hex",
        "GPRS ciphering key",
    ),
    (
        "DF.GSM",
        "EF.LOCIGPRS",
        0x6F53,
        'T',
        "loci",
        "GPRS location information",
    ),
    (
        "DF.GSM",
        "EF.SUME",
        0x6F54,
        'T',
        "hex",
        "SetUpMenu elements",
    ),
    (
        "DF.GSM",
        "EF.PLMNwAcT",
        0x6F60,
        'T',
        "plmn-act",
        "User controlled PLMN selector with access technology",
    ),
    (
        "DF.GSM",
        "EF.OPLMNwAcT",
        0x6F61,
        'T',
        "plmn-act",
        "Operator controlled PLMN selector with access technology",
    ),
    (
        "DF.GSM",
        "EF.HPLMNwAcT",
        0x6F62,
        'T',
        "plmn-act",
        "HPLMN selector with access technology",
    ),
    (
        "DF.GSM",
        "EF.CPBCCH",
        0x6F63,
        'T',
        "hex",
        "CPBCCH information",
    ),
    (
        "DF.GSM",
        "EF.INVSCAN",
        0x6F64,
        'T',
        "hex",
        "Investigation scan",
    ),
    (
        "DF.GSM",
        "EF.BCCH",
        0x6F74,
        'T',
        "hex",
        "Broadcast control channels",
    ),
    (
        "DF.GSM",
        "EF.ACC",
        0x6F78,
        'T',
        "acc",
        "Access control class",
    ),
    (
        "DF.GSM",
        "EF.FPLMN",
        0x6F7B,
        'T',
        "plmn-list",
        "Forbidden PLMNs",
    ),
    (
        "DF.GSM",
        "EF.LOCI",
        0x6F7E,
        'T',
        "loci",
        "Location information",
    ),
    ("DF.GSM", "EF.AD", 0x6FAD, 'T', "ad", "Administrative data"),
    (
        "DF.GSM",
        "EF.Phase",
        0x6FAE,
        'T',
        "uint",
        "Phase identification",
    ),
    (
        "DF.GSM",
        "EF.VGCS",
        0x6FB1,
        'T',
        "hex",
        "Voice group call service",
    ),
    (
        "DF.GSM",
        "EF.VGCSS",
        0x6FB2,
        'T',
        "hex",
        "Voice group call service status",
    ),
    (
        "DF.GSM",
        "EF.VBS",
        0x6FB3,
        'T',
        "hex",
        "Voice broadcast service",
    ),
    (
        "DF.GSM",
        "EF.VBSS",
        0x6FB4,
        'T',
        "hex",
        "Voice broadcast service status",
    ),
    (
        "DF.GSM",
        "EF.eMLPP",
        0x6FB5,
        'T',
        "hex",
        "Enhanced multi level pre-emption and priority",
    ),
    (
        "DF.GSM",
        "EF.AAeM",
        0x6FB6,
        'T',
        "hex",
        "Automatic answer for eMLPP service",
    ),
    (
        "DF.GSM",
        "EF.ECC",
        0x6FB7,
        'T',
        "ecc",
        "Emergency call codes",
    ),
    ("DF.GSM", "EF.PNN", 0x6FC5, 'L', "tlv", "PLMN network name"),
    ("DF.GSM", "EF.OPL", 0x6FC6, 'L', "opl", "Operator PLMN list"),
    (
        "DF.GSM",
        "EF.MBDN",
        0x6FC7,
        'L',
        "adn",
        "Mailbox dialling numbers",
    ),
    ("DF.GSM", "EF.EXT6", 0x6FC8, 'L', "hex", "Extension 6"),
    ("DF.GSM", "EF.MBI", 0x6FC9, 'L', "hex", "Mailbox identifier"),
    (
        "DF.GSM",
        "EF.MWIS",
        0x6FCA,
        'L',
        "hex",
        "Message waiting indication status",
    ),
    (
        "DF.GSM",
        "EF.CFIS",
        0x6FCB,
        'L',
        "hex",
        "Call forwarding indication status",
    ),
    ("DF.GSM", "EF.EXT7", 0x6FCC, 'L', "hex", "Extension 7"),
    (
        "DF.GSM",
        "EF.SPDI",
        0x6FCD,
        'T',
        "tlv",
        "Service provider display information",
    ),
    ("DF.GSM", "EF.MMSN", 0x6FCE, 'L', "hex", "MMS notification"),
    ("DF.GSM", "EF.EXT8", 0x6FCF, 'L', "hex", "Extension 8"),
    (
        "DF.GSM",
        "EF.MMSICP",
        0x6FD0,
        'T',
        "tlv",
        "MMS issuer connectivity parameters",
    ),
    (
        "DF.GSM",
        "EF.MMSUP",
        0x6FD1,
        'L',
        "hex",
        "MMS user preferences",
    ),
    (
        "DF.GSM",
        "EF.MMSUCP",
        0x6FD2,
        'T',
        "tlv",
        "MMS user connectivity parameters",
    ),
    (
        "DF.GSM-ACCESS",
        "EF.Kc",
        0x4F20,
        'T',
        "hex",
        "Ciphering key Kc",
    ),
    (
        "DF.GSM-ACCESS",
        "EF.KcGPRS",
        0x4F52,
        'T',
        "hex",
        "GPRS ciphering key",
    ),
    (
        "DF.GSM-ACCESS",
        "EF.CPBCCH",
        0x4F63,
        'T',
        "hex",
        "CPBCCH information",
    ),
    (
        "DF.GSM-ACCESS",
        "EF.InvScan",
        0x4F64,
        'T',
        "hex",
        "Investigation scan",
    ),
    (
        "DF.HNB",
        "EF.ACSGL",
        0x4F81,
        'L',
        "tlv",
        "Allowed CSG lists",
    ),
    ("DF.HNB", "EF.CSGT", 0x4F82, 'L', "tlv", "CSG type"),
    (
        "DF.HNB",
        "EF.HNBN",
        0x4F83,
        'L',
        "tlv",
        "Home (e)NodeB name",
    ),
    (
        "DF.HNB",
        "EF.OCSGL",
        0x4F84,
        'L',
        "tlv",
        "Operator CSG lists",
    ),
    (
        "DF.HNB",
        "EF.OCSGT",
        0x4F85,
        'L',
        "tlv",
        "Operator CSG type",
    ),
    (
        "DF.HNB",
        "EF.OHNBN",
        0x4F86,
        'L',
        "tlv",
        "Operator home (e)NodeB name",
    ),
    (
        "DF.MExE",
        "EF.MexE-ST",
        0x4F40,
        'T',
        "hex",
        "MExE service table",
    ),
    (
        "DF.MExE",
        "EF.ORPK",
        0x4F41,
        'L',
        "hex",
        "Operator root public key",
    ),
    (
        "DF.MExE",
        "EF.ARPK",
        0x4F42,
        'L',
        "hex",
        "Administrator root public key",
    ),
    (
        "DF.MExE",
        "EF.TPRK",
        0x4F43,
        'L',
        "hex",
        "Third party root public key",
    ),
    (
        "DF.MULTIMEDIA",
        "EF.MML",
        0x4F47,
        'B',
        "tlv",
        "Multimedia messages list",
    ),
    (
        "DF.MULTIMEDIA",
        "EF.MMDF",
        0x4F48,
        'T',
        "hex",
        "Multimedia messages data file",
    ),
    (
        "DF.PHONEBOOK",
        "EF.PBC",
        0x4F09,
        'L',
        "hex",
        "Phone book control",
    ),
    (
        "DF.PHONEBOOK",
        "EF.ANR",
        0x4F11,
        'L',
        "hex",
        "Additional number",
    ),
    (
        "DF.PHONEBOOK",
        "EF.SNE",
        0x4F19,
        'L',
        "hex",
        "Second name entry",
    ),
    (
        "DF.PHONEBOOK",
        "EF.UID",
        0x4F21,
        'L',
        "uint",
        "Unique identifier",
    ),
    (
        "DF.PHONEBOOK",
        "EF.PSC",
        0x4F22,
        'T',
        "hex",
        "Phone book synchronization counter",
    ),
    (
        "DF.PHONEBOOK",
        "EF.CC",
        0x4F23,
        'T',
        "uint",
        "Change counter",
    ),
    (
        "DF.PHONEBOOK",
        "EF.PUID",
        0x4F24,
        'T',
        "uint",
        "Previous unique identifier",
    ),
    (
        "DF.PHONEBOOK",
        "EF.IAP",
        0x4F25,
        'L',
        "hex",
        "Index administration phone book",
    ),
    (
        "DF.PHONEBOOK",
        "EF.GRP",
        0x4F26,
        'L',
        "hex",
        "Grouping information",
    ),
    (
        "DF.PHONEBOOK",
        "EF.PBR",
        0x4F30,
        'L',
        "tlv",
        "Phone book reference file",
    ),
    (
        "DF.PHONEBOOK",
        "EF.ADN",
        0x4F3A,
        'L',
        "adn",
        "Abbreviated dialling numbers (phone book)",
    ),
    (
        "DF.PHONEBOOK",
        "EF.EXT1",
        0x4F4A,
        'L',
        "hex",
        "Extension 1 (phone book)",
    ),
    (
        "DF.PHONEBOOK",
        "EF.AAS",
        0x4F4C,
        'L',
        "hex",
        "Additional number alpha string",
    ),
    (
        "DF.PHONEBOOK",
        "EF.GAS",
        0x4F4D,
        'L',
        "hex",
        "Grouping information alpha string",
    ),
    (
        "DF.PHONEBOOK",
        "EF.EMAIL",
        0x4F50,
        'L',
        "hex",
        "Email address",
    ),
    (
        "DF.ProSe",
        "EF.PROSE_MON",
        0x4F01,
        'L',
        "hex",
        "ProSe monitoring parameters",
    ),
    (
        "DF.ProSe",
        "EF.PROSE_RADIO_COM",
        0x4F04,
        'T',
        "hex",
        "ProSe direct communication radio parameters",
    ),
    (
        "DF.SAIP",
        "EF.SUCI_Calc_Info",
        0x4F01,
        'T',
        "suci",
        "SUCI calculation information (SAIP)",
    ),
    (
        "DF.SNPN",
        "EF.PWS_SNPN",
        0x4F01,
        'T',
        "hex",
        "Public warning system in SNPNs",
    ),
    (
        "DF.SNPN",
        "EF.NID",
        0x4F02,
        'L',
        "hex",
        "Network identifier for SNPN",
    ),
    (
        "DF.SoLSA",
        "EF.SAI",
        0x4F30,
        'T',
        "hex",
        "SoLSA access indicator",
    ),
    ("DF.SoLSA", "EF.SLL", 0x4F31, 'L', "hex", "SoLSA LSA list"),
    (
        "DF.TELECOM",
        "EF.ADN",
        0x6F3A,
        'L',
        "adn",
        "Abbreviated dialling numbers",
    ),
    (
        "DF.TELECOM",
        "EF.FDN",
        0x6F3B,
        'L',
        "adn",
        "Fixed dialling numbers",
    ),
    ("DF.TELECOM", "EF.SMS", 0x6F3C, 'L', "sms", "Short messages"),
    (
        "DF.TELECOM",
        "EF.CCP",
        0x6F3D,
        'L',
        "hex",
        "Capability configuration parameters",
    ),
    ("DF.TELECOM", "EF.MSISDN", 0x6F40, 'L', "adn", "MSISDN"),
    (
        "DF.TELECOM",
        "EF.SMSP",
        0x6F42,
        'L',
        "smsp",
        "Short message service parameters",
    ),
    ("DF.TELECOM", "EF.SMSS", 0x6F43, 'T', "smss", "SMS status"),
    (
        "DF.TELECOM",
        "EF.LND",
        0x6F44,
        'C',
        "adn",
        "Last number dialled",
    ),
    (
        "DF.TELECOM",
        "EF.SMSR",
        0x6F47,
        'L',
        "hex",
        "Short message status reports",
    ),
    (
        "DF.TELECOM",
        "EF.SDN",
        0x6F49,
        'L',
        "adn",
        "Service dialling numbers",
    ),
    ("DF.TELECOM", "EF.EXT1", 0x6F4A, 'L', "hex", "Extension 1"),
    ("DF.TELECOM", "EF.EXT2", 0x6F4B, 'L', "hex", "Extension 2"),
    ("DF.TELECOM", "EF.EXT3", 0x6F4C, 'L', "hex", "Extension 3"),
    (
        "DF.TELECOM",
        "EF.BDN",
        0x6F4D,
        'L',
        "adn",
        "Barred dialling numbers",
    ),
    ("DF.TELECOM", "EF.EXT4", 0x6F4E, 'L', "hex", "Extension 4"),
    (
        "DF.TELECOM",
        "EF.ECCP",
        0x6F4F,
        'L',
        "hex",
        "Extended capability configuration parameters",
    ),
    (
        "DF.TELECOM",
        "EF.ICE_DN",
        0x6FE0,
        'L',
        "adn",
        "In case of emergency dialling number",
    ),
    (
        "DF.TELECOM",
        "EF.ICE_FF",
        0x6FE1,
        'L',
        "hex",
        "In case of emergency free format",
    ),
    ("DF.WLAN", "EF.Pseudo", 0x4F41, 'T', "hex", "Pseudonym"),
    (
        "DF.WLAN",
        "EF.UPLMNWLAN",
        0x4F42,
        'T',
        "hex",
        "User controlled PLMN selector for I-WLAN access",
    ),
    (
        "DF.WLAN",
        "EF.OPLMNWLAN",
        0x4F43,
        'T',
        "hex",
        "Operator controlled PLMN selector for I-WLAN access",
    ),
    (
        "DF.WLAN",
        "EF.UWSIDL",
        0x4F44,
        'L',
        "hex",
        "User controlled WSID list",
    ),
    (
        "DF.WLAN",
        "EF.OWSIDL",
        0x4F45,
        'L',
        "hex",
        "Operator controlled WSID list",
    ),
    (
        "DF.WLAN",
        "EF.WRI",
        0x4F46,
        'T',
        "hex",
        "WLAN reauthentication identity",
    ),
    (
        "DF.WLAN",
        "EF.HWSIDL",
        0x4F47,
        'L',
        "hex",
        "Home I-WLAN specific identifier list",
    ),
    (
        "DF.WLAN",
        "EF.WEHPLMNPI",
        0x4F48,
        'T',
        "uint",
        "I-WLAN equivalent HPLMN presentation indication",
    ),
    (
        "DF.WLAN",
        "EF.WHPI",
        0x4F49,
        'T',
        "uint",
        "I-WLAN HPLMN priority indication",
    ),
    (
        "DF.WLAN",
        "EF.WLRPLMN",
        0x4F4A,
        'T',
        "hex",
        "I-WLAN last registered PLMN",
    ),
    (
        "DF.WLAN",
        "EF.HPLMNDAI",
        0x4F4B,
        'T',
        "hex",
        "HPLMN direct access indicator",
    ),
    ("MF", "EF.DIR", 0x2F00, 'L', "tlv", "Application directory"),
    (
        "MF",
        "EF.PL",
        0x2F05,
        'T',
        "alpha-list",
        "Preferred languages",
    ),
    ("MF", "EF.ARR", 0x2F06, 'L', "tlv", "Access rule reference"),
    (
        "MF",
        "EF.UMPC",
        0x2F08,
        'T',
        "uint",
        "UICC maximum power consumption",
    ),
    ("MF", "EF.ICCID", 0x2FE2, 'T', "iccid", "ICC identification"),
];
